### PR TITLE
Catkinize rqt experimental

### PR DESCRIPTION
**Pull request by furushchev**
I think it's time to release `rqt_smach` to deb. This is one of the most useful visualisation tool that is too early to be forgotten. :-)

[Review on Reviewable](https://reviewable.io/reviews/ros-visualization/executive_smach_visualization/10)

### CODE REVIEW

**Comment by furushchev** [comment]
ping

**Comment by furushchev** [comment]
ping

**Comment by 130s** [comment]
@furushchev Could you provide us any simple test case / how to run smach
nodes so that we can test the visual?
The code LGTM, it even runs on my machine too. I just want to test seeing
stuff on it.

**Comment by jbohren** [comment]
Smach should really just have some built-in examples to test these things.
It really hasn't gotten much love in the last few years, but I need to set
aside some time to merge a bunch of contributions and release.

**Pull request closed without merging**
