### PR TITLE
[FIX] 'Jump' object has no attribute 'url'

### PR DESCRIPTION
**Pull request by Combinacijus**
Fix for AttributeError: 'Jump' object has no attribute 'url'
To reproduce:

- roscore
- rosrun smach_viewer smach_viewer.py
- Press "+" button to increase depth and hover over/click text "Path not available"
- Error prints in terminal

### CODE REVIEW

**Comment by k-okada** [comment]
thaks for contribution, please create PR against our latest `melodic-devel` branch https://github.com/ros-visualization/executive_smach_visualization/tree/melodic-devel

**Comment by Combinacijus** [comment]
@k-okada changed it to `melodic-devel`. But I would guess same problem occurs in other branches too.

**Comment by k-okada** [comment]
@Combinacijus thanks! can you fix
```
 Sorry: IndentationError: unindent does not match any outer indentation level (smach_viewer.py, line 713)
```
error?

**Comment by Combinacijus** [comment]
@k-okada oh sorry for such a silly mistake. That's what you get by editing files inside Github.
Now it's strange to have two commits I'm still learning how Github works so is it normal to have many commits to fix initial commit? I would say a single commit with all the final changes would look nicer

**Comment by k-okada** [comment]
@Combinacijus thaks, I also prefer single commit, for simple fix, but it is ok for now.

**Pull request merged**
