### PR TITLE
Allow launching from a launch file, use rospy.myargv() to remove ROS remapping arguments

### PR DESCRIPTION
**Pull request by kartikmohta**
Required to allow launching from a launch file, otherwise get errors of the type:
```
usage: smach_viewer.py [-h] [-f]
smach_viewer.py: error: unrecognized arguments: __name:=smach_viewer
```

### CODE REVIEW

**Comment by furushchev** [comment]
+1 for the bugfix, though there are also lots of unrelated changes included...

**Comment by furushchev** [comment]
Just to clarify, without this PR, launching `smach_viewer` from `launch` file fails:

```xml
<launch>
  <node name="smach_viewer" pkg="smach_viewer" type="smach_viewer.py" />
</launch>
```

```bash
SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    smach_viewer (smach_viewer/smach_viewer.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[smach_viewer-1]: started with pid [15151]
usage: smach_viewer.py [-h] [-f]
smach_viewer.py: error: unrecognized arguments: __name:=smach_viewer __log:=/home/furushchev/.ros/log/30411004-78dc-11e7-8090-a434d9dcb7b6/smach_viewer-1.log
[smach_viewer-1] process has died [pid 15151, exit code 2, cmd /opt/ros/indigo/lib/smach_viewer/smach_viewer.py __name:=smach_viewer __log:=/home/furushchev/.ros/log/30411004-78dc-11e7-8090-a434d9dcb7b6/smach_viewer-1.log].
log file: /home/furushchev/.ros/log/30411004-78dc-11e7-8090-a434d9dcb7b6/smach_viewer-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by kartikmohta** [comment]
@furushchev Just add `?w=1` to the end of the URL to ignore the whitespace changes when looking at the commit changes.

**Comment by furushchev** [comment]
@kartikmohta I think the change rather should be in another pull request.

**Comment by snozawa** [comment]
+1 for the bugfix in this PR!

+1 for handling of the whitespace : https://github.com/ros-visualization/executive_smach_visualization/pull/16#issuecomment-320172263

**Comment by furushchev** [comment]
@kartikmohta Thanks! Now It's much clear and +1 more to be merged!

**Comment by snozawa** [comment]
@kartikmohta 
Thanks a lot!

**Comment by StephanHasler** [comment]
+1 The proposed solution works for me. It solves issue: #17

**Comment by mk-nk** [comment]
+1 for the bugfix #17

**Comment by k-okada** [comment]
merged and released https://github.com/ros/rosdistro/pull/16169

**Pull request merged**
